Started by user [8mha:AAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzREgZu/dLi1CL9nNSi7HwATSuZe8AAAAA=[0mLerko Araya Hernandez
Building in workspace /var/lib/jenkins/workspace/AlertingTest
No emails were triggered.
[AlertingTest] $ /bin/sh -xe /tmp/hudson9198177762024545917.sh
+ python -u /home/lerko/Desktop/ComplexBehaviorDetector/DetectorsType1.py AlertingDetector CRITICAL
Traceback (most recent call last):
  File "/home/lerko/Desktop/ComplexBehaviorDetector/DetectorsType1.py", line 110, in <module>
    main(sys.argv[1:])
  File "/home/lerko/Desktop/ComplexBehaviorDetector/DetectorsType1.py", line 99, in main
    myDetector = AlertingTestDetector(priority)
  File "/home/lerko/Desktop/ComplexBehaviorDetector/DetectorsType1.py", line 56, in __init__
    BaseDetector.__init__(self, priority)
  File "/home/lerko/Desktop/ComplexBehaviorDetector/DetectorsType1.py", line 14, in __init__
    self.errorLogPath = os.path.dirname(os.path.realpath(__file__)) + '/log/historical.log'
NameError: global name 'os' is not defined
Build step 'Run with timeout' marked build as failure
No emails were triggered.
Finished: FAILURE
